export const SERVER_URL = "http://localhost:8000/"
export const LOGIN_URL = "api/users/login"
export const SIGNUP_URL = "api/users"
export const COUNTRIES_URL = "api/country"
export const STATE_URL = "api/state"
export const CITY_URL = "api/city"